// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.34.1
// source: activity/contract.proto

package activity

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	emptypb "google.golang.org/protobuf/types/known/emptypb"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type Activity struct {
	state                protoimpl.MessageState `protogen:"open.v1"`
	ActivityId           uint64                 `protobuf:"varint,1,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	CreatedAt            *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt            *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	IsActive             bool                   `protobuf:"varint,4,opt,name=is_active,json=isActive,proto3" json:"is_active,omitempty"`
	Name                 string                 `protobuf:"bytes,5,opt,name=name,proto3" json:"name,omitempty"`
	Description          string                 `protobuf:"bytes,6,opt,name=description,proto3" json:"description,omitempty"`
	ActivityPlaceId      uint64                 `protobuf:"varint,7,opt,name=activity_place_id,json=activityPlaceId,proto3" json:"activity_place_id,omitempty"`
	RegisteredUsersCount uint64                 `protobuf:"varint,8,opt,name=registered_users_count,json=registeredUsersCount,proto3" json:"registered_users_count,omitempty"`
	IsUserRegistered     *bool                  `protobuf:"varint,9,opt,name=is_user_registered,json=isUserRegistered,proto3,oneof" json:"is_user_registered,omitempty"`
	StartsAt             *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=starts_at,json=startsAt,proto3,oneof" json:"starts_at,omitempty"`
	EndsAt               *timestamppb.Timestamp `protobuf:"bytes,11,opt,name=ends_at,json=endsAt,proto3,oneof" json:"ends_at,omitempty"`
	RegistrationUntil    *timestamppb.Timestamp `protobuf:"bytes,12,opt,name=registration_until,json=registrationUntil,proto3,oneof" json:"registration_until,omitempty"`
	unknownFields        protoimpl.UnknownFields
	sizeCache            protoimpl.SizeCache
}

func (x *Activity) Reset() {
	*x = Activity{}
	mi := &file_activity_contract_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Activity) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Activity) ProtoMessage() {}

func (x *Activity) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Activity.ProtoReflect.Descriptor instead.
func (*Activity) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{0}
}

func (x *Activity) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *Activity) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *Activity) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

func (x *Activity) GetIsActive() bool {
	if x != nil {
		return x.IsActive
	}
	return false
}

func (x *Activity) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *Activity) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *Activity) GetActivityPlaceId() uint64 {
	if x != nil {
		return x.ActivityPlaceId
	}
	return 0
}

func (x *Activity) GetRegisteredUsersCount() uint64 {
	if x != nil {
		return x.RegisteredUsersCount
	}
	return 0
}

func (x *Activity) GetIsUserRegistered() bool {
	if x != nil && x.IsUserRegistered != nil {
		return *x.IsUserRegistered
	}
	return false
}

func (x *Activity) GetStartsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.StartsAt
	}
	return nil
}

func (x *Activity) GetEndsAt() *timestamppb.Timestamp {
	if x != nil {
		return x.EndsAt
	}
	return nil
}

func (x *Activity) GetRegistrationUntil() *timestamppb.Timestamp {
	if x != nil {
		return x.RegistrationUntil
	}
	return nil
}

type BaseRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BaseRequest) Reset() {
	*x = BaseRequest{}
	mi := &file_activity_contract_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BaseRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BaseRequest) ProtoMessage() {}

func (x *BaseRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BaseRequest.ProtoReflect.Descriptor instead.
func (*BaseRequest) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{1}
}

func (x *BaseRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

type IdempotentRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	UserId          string                 `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3" json:"user_id,omitempty"`
	DeduplicationId string                 `protobuf:"bytes,2,opt,name=deduplication_id,json=deduplicationId,proto3" json:"deduplication_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *IdempotentRequest) Reset() {
	*x = IdempotentRequest{}
	mi := &file_activity_contract_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IdempotentRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IdempotentRequest) ProtoMessage() {}

func (x *IdempotentRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IdempotentRequest.ProtoReflect.Descriptor instead.
func (*IdempotentRequest) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{2}
}

func (x *IdempotentRequest) GetUserId() string {
	if x != nil {
		return x.UserId
	}
	return ""
}

func (x *IdempotentRequest) GetDeduplicationId() string {
	if x != nil {
		return x.DeduplicationId
	}
	return ""
}

type GetActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivitiesRequest) Reset() {
	*x = GetActivitiesRequest{}
	mi := &file_activity_contract_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivitiesRequest) ProtoMessage() {}

func (x *GetActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivitiesRequest.ProtoReflect.Descriptor instead.
func (*GetActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{3}
}

func (x *GetActivitiesRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

type CreateActivityRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Base            *IdempotentRequest     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	Name            string                 `protobuf:"bytes,2,opt,name=name,proto3" json:"name,omitempty"`
	Description     string                 `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	ActivityPlaceId uint64                 `protobuf:"varint,4,opt,name=activity_place_id,json=activityPlaceId,proto3" json:"activity_place_id,omitempty"`
	ImageUrl        string                 `protobuf:"bytes,5,opt,name=imageUrl,proto3" json:"imageUrl,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *CreateActivityRequest) Reset() {
	*x = CreateActivityRequest{}
	mi := &file_activity_contract_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateActivityRequest) ProtoMessage() {}

func (x *CreateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateActivityRequest.ProtoReflect.Descriptor instead.
func (*CreateActivityRequest) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{4}
}

func (x *CreateActivityRequest) GetBase() *IdempotentRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *CreateActivityRequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateActivityRequest) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateActivityRequest) GetActivityPlaceId() uint64 {
	if x != nil {
		return x.ActivityPlaceId
	}
	return 0
}

func (x *CreateActivityRequest) GetImageUrl() string {
	if x != nil {
		return x.ImageUrl
	}
	return ""
}

type GetActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	UserId        *string                `protobuf:"bytes,1,opt,name=user_id,json=userId,proto3,oneof" json:"user_id,omitempty"`
	ActivityId    uint64                 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetActivityRequest) Reset() {
	*x = GetActivityRequest{}
	mi := &file_activity_contract_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetActivityRequest) ProtoMessage() {}

func (x *GetActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetActivityRequest.ProtoReflect.Descriptor instead.
func (*GetActivityRequest) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{5}
}

func (x *GetActivityRequest) GetUserId() string {
	if x != nil && x.UserId != nil {
		return *x.UserId
	}
	return ""
}

func (x *GetActivityRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type UpdateActivityRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	Base            *IdempotentRequest     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ActivityId      uint64                 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	IsActive        *bool                  `protobuf:"varint,3,opt,name=is_active,json=isActive,proto3,oneof" json:"is_active,omitempty"`
	Name            *string                `protobuf:"bytes,4,opt,name=name,proto3,oneof" json:"name,omitempty"`
	Description     *string                `protobuf:"bytes,5,opt,name=description,proto3,oneof" json:"description,omitempty"`
	ActivityPlaceId *uint64                `protobuf:"varint,6,opt,name=activity_place_id,json=activityPlaceId,proto3,oneof" json:"activity_place_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *UpdateActivityRequest) Reset() {
	*x = UpdateActivityRequest{}
	mi := &file_activity_contract_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *UpdateActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*UpdateActivityRequest) ProtoMessage() {}

func (x *UpdateActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use UpdateActivityRequest.ProtoReflect.Descriptor instead.
func (*UpdateActivityRequest) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{6}
}

func (x *UpdateActivityRequest) GetBase() *IdempotentRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *UpdateActivityRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

func (x *UpdateActivityRequest) GetIsActive() bool {
	if x != nil && x.IsActive != nil {
		return *x.IsActive
	}
	return false
}

func (x *UpdateActivityRequest) GetName() string {
	if x != nil && x.Name != nil {
		return *x.Name
	}
	return ""
}

func (x *UpdateActivityRequest) GetDescription() string {
	if x != nil && x.Description != nil {
		return *x.Description
	}
	return ""
}

func (x *UpdateActivityRequest) GetActivityPlaceId() uint64 {
	if x != nil && x.ActivityPlaceId != nil {
		return *x.ActivityPlaceId
	}
	return 0
}

type DeleteActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *IdempotentRequest     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ActivityId    uint64                 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteActivityRequest) Reset() {
	*x = DeleteActivityRequest{}
	mi := &file_activity_contract_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteActivityRequest) ProtoMessage() {}

func (x *DeleteActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteActivityRequest.ProtoReflect.Descriptor instead.
func (*DeleteActivityRequest) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{7}
}

func (x *DeleteActivityRequest) GetBase() *IdempotentRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *DeleteActivityRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type RegisterUserActivityRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *IdempotentRequest     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ActivityId    uint64                 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RegisterUserActivityRequest) Reset() {
	*x = RegisterUserActivityRequest{}
	mi := &file_activity_contract_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RegisterUserActivityRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RegisterUserActivityRequest) ProtoMessage() {}

func (x *RegisterUserActivityRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RegisterUserActivityRequest.ProtoReflect.Descriptor instead.
func (*RegisterUserActivityRequest) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{8}
}

func (x *RegisterUserActivityRequest) GetBase() *IdempotentRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *RegisterUserActivityRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type ActivitySeenRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *IdempotentRequest     `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	ActivityId    uint64                 `protobuf:"varint,2,opt,name=activity_id,json=activityId,proto3" json:"activity_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivitySeenRequest) Reset() {
	*x = ActivitySeenRequest{}
	mi := &file_activity_contract_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivitySeenRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivitySeenRequest) ProtoMessage() {}

func (x *ActivitySeenRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivitySeenRequest.ProtoReflect.Descriptor instead.
func (*ActivitySeenRequest) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{9}
}

func (x *ActivitySeenRequest) GetBase() *IdempotentRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

func (x *ActivitySeenRequest) GetActivityId() uint64 {
	if x != nil {
		return x.ActivityId
	}
	return 0
}

type GetUserActivitiesRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Base          *BaseRequest           `protobuf:"bytes,1,opt,name=base,proto3" json:"base,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetUserActivitiesRequest) Reset() {
	*x = GetUserActivitiesRequest{}
	mi := &file_activity_contract_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetUserActivitiesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetUserActivitiesRequest) ProtoMessage() {}

func (x *GetUserActivitiesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetUserActivitiesRequest.ProtoReflect.Descriptor instead.
func (*GetUserActivitiesRequest) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{10}
}

func (x *GetUserActivitiesRequest) GetBase() *BaseRequest {
	if x != nil {
		return x.Base
	}
	return nil
}

type ActivityResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          *Activity              `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivityResponse) Reset() {
	*x = ActivityResponse{}
	mi := &file_activity_contract_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivityResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivityResponse) ProtoMessage() {}

func (x *ActivityResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivityResponse.ProtoReflect.Descriptor instead.
func (*ActivityResponse) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{11}
}

func (x *ActivityResponse) GetData() *Activity {
	if x != nil {
		return x.Data
	}
	return nil
}

type ActivitiesResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Data          []*Activity            `protobuf:"bytes,1,rep,name=data,proto3" json:"data,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ActivitiesResponse) Reset() {
	*x = ActivitiesResponse{}
	mi := &file_activity_contract_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ActivitiesResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ActivitiesResponse) ProtoMessage() {}

func (x *ActivitiesResponse) ProtoReflect() protoreflect.Message {
	mi := &file_activity_contract_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ActivitiesResponse.ProtoReflect.Descriptor instead.
func (*ActivitiesResponse) Descriptor() ([]byte, []int) {
	return file_activity_contract_proto_rawDescGZIP(), []int{12}
}

func (x *ActivitiesResponse) GetData() []*Activity {
	if x != nil {
		return x.Data
	}
	return nil
}

var File_activity_contract_proto protoreflect.FileDescriptor

const file_activity_contract_proto_rawDesc = "" +
	"\n" +
	"\x17activity/contract.proto\x12\x10activity_service\x1a\x1fgoogle/protobuf/timestamp.proto\x1a\x1bgoogle/protobuf/empty.proto\"\x99\x05\n" +
	"\bActivity\x12\x1f\n" +
	"\vactivity_id\x18\x01 \x01(\x04R\n" +
	"activityId\x129\n" +
	"\n" +
	"created_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\x12\x1b\n" +
	"\tis_active\x18\x04 \x01(\bR\bisActive\x12\x12\n" +
	"\x04name\x18\x05 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x06 \x01(\tR\vdescription\x12*\n" +
	"\x11activity_place_id\x18\a \x01(\x04R\x0factivityPlaceId\x124\n" +
	"\x16registered_users_count\x18\b \x01(\x04R\x14registeredUsersCount\x121\n" +
	"\x12is_user_registered\x18\t \x01(\bH\x00R\x10isUserRegistered\x88\x01\x01\x12<\n" +
	"\tstarts_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampH\x01R\bstartsAt\x88\x01\x01\x128\n" +
	"\aends_at\x18\v \x01(\v2\x1a.google.protobuf.TimestampH\x02R\x06endsAt\x88\x01\x01\x12N\n" +
	"\x12registration_until\x18\f \x01(\v2\x1a.google.protobuf.TimestampH\x03R\x11registrationUntil\x88\x01\x01B\x15\n" +
	"\x13_is_user_registeredB\f\n" +
	"\n" +
	"_starts_atB\n" +
	"\n" +
	"\b_ends_atB\x15\n" +
	"\x13_registration_until\"&\n" +
	"\vBaseRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\"W\n" +
	"\x11IdempotentRequest\x12\x17\n" +
	"\auser_id\x18\x01 \x01(\tR\x06userId\x12)\n" +
	"\x10deduplication_id\x18\x02 \x01(\tR\x0fdeduplicationId\"@\n" +
	"\x14GetActivitiesRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x88\x01\x01B\n" +
	"\n" +
	"\b_user_id\"\xce\x01\n" +
	"\x15CreateActivityRequest\x127\n" +
	"\x04base\x18\x01 \x01(\v2#.activity_service.IdempotentRequestR\x04base\x12\x12\n" +
	"\x04name\x18\x02 \x01(\tR\x04name\x12 \n" +
	"\vdescription\x18\x03 \x01(\tR\vdescription\x12*\n" +
	"\x11activity_place_id\x18\x04 \x01(\x04R\x0factivityPlaceId\x12\x1a\n" +
	"\bimageUrl\x18\x05 \x01(\tR\bimageUrl\"_\n" +
	"\x12GetActivityRequest\x12\x1c\n" +
	"\auser_id\x18\x01 \x01(\tH\x00R\x06userId\x88\x01\x01\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x04R\n" +
	"activityIdB\n" +
	"\n" +
	"\b_user_id\"\xc1\x02\n" +
	"\x15UpdateActivityRequest\x127\n" +
	"\x04base\x18\x01 \x01(\v2#.activity_service.IdempotentRequestR\x04base\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x04R\n" +
	"activityId\x12 \n" +
	"\tis_active\x18\x03 \x01(\bH\x00R\bisActive\x88\x01\x01\x12\x17\n" +
	"\x04name\x18\x04 \x01(\tH\x01R\x04name\x88\x01\x01\x12%\n" +
	"\vdescription\x18\x05 \x01(\tH\x02R\vdescription\x88\x01\x01\x12/\n" +
	"\x11activity_place_id\x18\x06 \x01(\x04H\x03R\x0factivityPlaceId\x88\x01\x01B\f\n" +
	"\n" +
	"_is_activeB\a\n" +
	"\x05_nameB\x0e\n" +
	"\f_descriptionB\x14\n" +
	"\x12_activity_place_id\"q\n" +
	"\x15DeleteActivityRequest\x127\n" +
	"\x04base\x18\x01 \x01(\v2#.activity_service.IdempotentRequestR\x04base\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x04R\n" +
	"activityId\"w\n" +
	"\x1bRegisterUserActivityRequest\x127\n" +
	"\x04base\x18\x01 \x01(\v2#.activity_service.IdempotentRequestR\x04base\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x04R\n" +
	"activityId\"o\n" +
	"\x13ActivitySeenRequest\x127\n" +
	"\x04base\x18\x01 \x01(\v2#.activity_service.IdempotentRequestR\x04base\x12\x1f\n" +
	"\vactivity_id\x18\x02 \x01(\x04R\n" +
	"activityId\"M\n" +
	"\x18GetUserActivitiesRequest\x121\n" +
	"\x04base\x18\x01 \x01(\v2\x1d.activity_service.BaseRequestR\x04base\"B\n" +
	"\x10ActivityResponse\x12.\n" +
	"\x04data\x18\x01 \x01(\v2\x1a.activity_service.ActivityR\x04data\"D\n" +
	"\x12ActivitiesResponse\x12.\n" +
	"\x04data\x18\x01 \x03(\v2\x1a.activity_service.ActivityR\x04data2\xae\a\n" +
	"\x0fActivityService\x12]\n" +
	"\x0eCreateActivity\x12'.activity_service.CreateActivityRequest\x1a\".activity_service.ActivityResponse\x12]\n" +
	"\rGetActivities\x12&.activity_service.GetActivitiesRequest\x1a$.activity_service.ActivitiesResponse\x12W\n" +
	"\vGetActivity\x12$.activity_service.GetActivityRequest\x1a\".activity_service.ActivityResponse\x12]\n" +
	"\x0eUpdateActivity\x12'.activity_service.UpdateActivityRequest\x1a\".activity_service.ActivityResponse\x12Q\n" +
	"\x0eDeleteActivity\x12'.activity_service.DeleteActivityRequest\x1a\x16.google.protobuf.Empty\x12i\n" +
	"\x14RegisterUserActivity\x12-.activity_service.RegisterUserActivityRequest\x1a\".activity_service.ActivityResponse\x12=\n" +
	"\vHealthCheck\x12\x16.google.protobuf.Empty\x1a\x16.google.protobuf.Empty\x12I\n" +
	"\bMarkSeen\x12%.activity_service.ActivitySeenRequest\x1a\x16.google.protobuf.Empty\x12l\n" +
	"\x18GetUserCreatedActivities\x12*.activity_service.GetUserActivitiesRequest\x1a$.activity_service.ActivitiesResponse\x12o\n" +
	"\x1bGetUserRegisteredActivities\x12*.activity_service.GetUserActivitiesRequest\x1a$.activity_service.ActivitiesResponseB:Z8https://github.com/Evensee/protobuf-definitions/activityb\x06proto3"

var (
	file_activity_contract_proto_rawDescOnce sync.Once
	file_activity_contract_proto_rawDescData []byte
)

func file_activity_contract_proto_rawDescGZIP() []byte {
	file_activity_contract_proto_rawDescOnce.Do(func() {
		file_activity_contract_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_activity_contract_proto_rawDesc), len(file_activity_contract_proto_rawDesc)))
	})
	return file_activity_contract_proto_rawDescData
}

var file_activity_contract_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_activity_contract_proto_goTypes = []any{
	(*Activity)(nil),                    // 0: activity_service.Activity
	(*BaseRequest)(nil),                 // 1: activity_service.BaseRequest
	(*IdempotentRequest)(nil),           // 2: activity_service.IdempotentRequest
	(*GetActivitiesRequest)(nil),        // 3: activity_service.GetActivitiesRequest
	(*CreateActivityRequest)(nil),       // 4: activity_service.CreateActivityRequest
	(*GetActivityRequest)(nil),          // 5: activity_service.GetActivityRequest
	(*UpdateActivityRequest)(nil),       // 6: activity_service.UpdateActivityRequest
	(*DeleteActivityRequest)(nil),       // 7: activity_service.DeleteActivityRequest
	(*RegisterUserActivityRequest)(nil), // 8: activity_service.RegisterUserActivityRequest
	(*ActivitySeenRequest)(nil),         // 9: activity_service.ActivitySeenRequest
	(*GetUserActivitiesRequest)(nil),    // 10: activity_service.GetUserActivitiesRequest
	(*ActivityResponse)(nil),            // 11: activity_service.ActivityResponse
	(*ActivitiesResponse)(nil),          // 12: activity_service.ActivitiesResponse
	(*timestamppb.Timestamp)(nil),       // 13: google.protobuf.Timestamp
	(*emptypb.Empty)(nil),               // 14: google.protobuf.Empty
}
var file_activity_contract_proto_depIdxs = []int32{
	13, // 0: activity_service.Activity.created_at:type_name -> google.protobuf.Timestamp
	13, // 1: activity_service.Activity.updated_at:type_name -> google.protobuf.Timestamp
	13, // 2: activity_service.Activity.starts_at:type_name -> google.protobuf.Timestamp
	13, // 3: activity_service.Activity.ends_at:type_name -> google.protobuf.Timestamp
	13, // 4: activity_service.Activity.registration_until:type_name -> google.protobuf.Timestamp
	2,  // 5: activity_service.CreateActivityRequest.base:type_name -> activity_service.IdempotentRequest
	2,  // 6: activity_service.UpdateActivityRequest.base:type_name -> activity_service.IdempotentRequest
	2,  // 7: activity_service.DeleteActivityRequest.base:type_name -> activity_service.IdempotentRequest
	2,  // 8: activity_service.RegisterUserActivityRequest.base:type_name -> activity_service.IdempotentRequest
	2,  // 9: activity_service.ActivitySeenRequest.base:type_name -> activity_service.IdempotentRequest
	1,  // 10: activity_service.GetUserActivitiesRequest.base:type_name -> activity_service.BaseRequest
	0,  // 11: activity_service.ActivityResponse.data:type_name -> activity_service.Activity
	0,  // 12: activity_service.ActivitiesResponse.data:type_name -> activity_service.Activity
	4,  // 13: activity_service.ActivityService.CreateActivity:input_type -> activity_service.CreateActivityRequest
	3,  // 14: activity_service.ActivityService.GetActivities:input_type -> activity_service.GetActivitiesRequest
	5,  // 15: activity_service.ActivityService.GetActivity:input_type -> activity_service.GetActivityRequest
	6,  // 16: activity_service.ActivityService.UpdateActivity:input_type -> activity_service.UpdateActivityRequest
	7,  // 17: activity_service.ActivityService.DeleteActivity:input_type -> activity_service.DeleteActivityRequest
	8,  // 18: activity_service.ActivityService.RegisterUserActivity:input_type -> activity_service.RegisterUserActivityRequest
	14, // 19: activity_service.ActivityService.HealthCheck:input_type -> google.protobuf.Empty
	9,  // 20: activity_service.ActivityService.MarkSeen:input_type -> activity_service.ActivitySeenRequest
	10, // 21: activity_service.ActivityService.GetUserCreatedActivities:input_type -> activity_service.GetUserActivitiesRequest
	10, // 22: activity_service.ActivityService.GetUserRegisteredActivities:input_type -> activity_service.GetUserActivitiesRequest
	11, // 23: activity_service.ActivityService.CreateActivity:output_type -> activity_service.ActivityResponse
	12, // 24: activity_service.ActivityService.GetActivities:output_type -> activity_service.ActivitiesResponse
	11, // 25: activity_service.ActivityService.GetActivity:output_type -> activity_service.ActivityResponse
	11, // 26: activity_service.ActivityService.UpdateActivity:output_type -> activity_service.ActivityResponse
	14, // 27: activity_service.ActivityService.DeleteActivity:output_type -> google.protobuf.Empty
	11, // 28: activity_service.ActivityService.RegisterUserActivity:output_type -> activity_service.ActivityResponse
	14, // 29: activity_service.ActivityService.HealthCheck:output_type -> google.protobuf.Empty
	14, // 30: activity_service.ActivityService.MarkSeen:output_type -> google.protobuf.Empty
	12, // 31: activity_service.ActivityService.GetUserCreatedActivities:output_type -> activity_service.ActivitiesResponse
	12, // 32: activity_service.ActivityService.GetUserRegisteredActivities:output_type -> activity_service.ActivitiesResponse
	23, // [23:33] is the sub-list for method output_type
	13, // [13:23] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_activity_contract_proto_init() }
func file_activity_contract_proto_init() {
	if File_activity_contract_proto != nil {
		return
	}
	file_activity_contract_proto_msgTypes[0].OneofWrappers = []any{}
	file_activity_contract_proto_msgTypes[3].OneofWrappers = []any{}
	file_activity_contract_proto_msgTypes[5].OneofWrappers = []any{}
	file_activity_contract_proto_msgTypes[6].OneofWrappers = []any{}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_activity_contract_proto_rawDesc), len(file_activity_contract_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_activity_contract_proto_goTypes,
		DependencyIndexes: file_activity_contract_proto_depIdxs,
		MessageInfos:      file_activity_contract_proto_msgTypes,
	}.Build()
	File_activity_contract_proto = out.File
	file_activity_contract_proto_goTypes = nil
	file_activity_contract_proto_depIdxs = nil
}
